### ISSUE TITLE
JSON API example?

### ISSUE THREAD

**Issue by bguiz** [rustless/rustless#25]
Looking at the [postgres example](https://github.com/rustless/rustless/blob/master/examples/postgres/src/main.rs),
and I am wondering if you would be able to extend this to conform to [JSON-API](http://jsonapi.org/),
with Create, Update, and Delete statements as well.

I have previously [attempted something like this using nickel.rs](https://github.com/bguiz/rust-scratch/blob/master/nickel-postgres/src/main.rs#L217),
as this is a use case that I have to satisfy before I can start writing back end code using rust.
I found it rather convoluted at the time with nickel,
and want to know if it would be any easier using rustless -
I'm certainly hoping so!

**Comment by s-panferov** [comment]
@bguiz thanks for the suggestion. I'll find some time today to clarify this.

**Comment by bguiz** [comment]
@s-panferov That would be really great fi you did. I'm looking through the rest of this project, thanks for putting it together!

**Comment by s-panferov** [comment]
@bguiz please see #28
