### ISSUE TITLE
Server stops accepting connections after a while

### ISSUE THREAD

**Issue by andor44** [rustless/rustless#35]
I have very little information regarding the issue yet, and this could be an Iron issue. The issue is basically that after some indeterminate amount of time (typically a few hours to a few days) the server seems to stop accepting new connections. It doesn't panic or return any errors anywhere, as far as I can tell. Any requests I attempt to make to it will time out.

**Comment by s-panferov** [comment]
@reem @seanmonstar have you seen something like this before?

@andor44 do you have code to reproduce?

**Comment by reem** [comment]
I haven't. I'm guessing there's a bug in hyper's `ListenerPool` that causes it to drop threads.

**Comment by seanmonstar** [comment]
Logs would also be useful, if possible (`RUST_LOG=hyper=trace` and usage of `env_logger`).

**Comment by andor44** [comment]
@s-panferov I do not have any, yet. I'll see if I can reproduce this with a minimal code example, but like I said, the problem is that this seems to manifest itself over time

@seanmonstar I provided that env var but I see no output whatsoever.

**Comment by seanmonstar** [comment]
@andor44 you need to set up a logger. The `env_logger` package on crates.io uses the env var.

**Comment by andor44** [comment]
@seanmonstar gotcha. I'll keep logging and see if I can catch anything.

**Comment by andor44** [comment]
Okay, I hit the point where it doesn't accept connections again. I can see a lot of 
`TRACE:hyper::http: TODO: handle obs-folding (gross!)`
But this doesn't seem very relevant. What seems more worrying is that every request seems to end in
```
DEBUG:hyper::http: read request line
DEBUG:hyper::server: ioerror in keepalive loop = HttpIoError(IoError { kind: EndOfFile, desc: "end of file", detail: None })
```
And then a new one begins again with `DEBUG:hyper::server: Incoming stream`. The last request that was processed didn't end up up in that error though.

**Comment by seanmonstar** [comment]
The EOF error is normal, it's how the server knows the connection was
closed. That's why it's only DEBUG. Unexpected errors log at ERROR.

However, EndOfFile errors were changed to something else with the new IO.
Are you using latest hyper?

**Comment by andor44** [comment]
I'm on 0.1.13 according to my `Cargo.lock`. I tried updating earlier last week but was unable to, due to deuterium being out of date IIRC.

**Comment by s-panferov** [comment]
@andor44 not it's ok, please try the new version.

**Comment by reem** [comment]
I am still just guessing, but what might be going on is that every thread in the pool is occupied in a keep-alive loop and the connections are never being closed.

**Comment by andor44** [comment]
I've updated to today's rustc nightly, plus all the highest versions available on crates.io (hyper 0.3.0, rustless 0.5.8). I'll let you know how it goes with this.

**Comment by s-panferov** [comment]
@reem maybe we can add some more debugging logging (in temp branch of hyper) to check your idea?

**Comment by andor44** [comment]
This still happens with hyper 0.3.0

**Comment by andor44** [comment]
The situation @reem described sounds very plausible, as these are mobile clients that are sending `Connection: keep-alive`. I'll try bump the number of threads until it's fixed. It'd be probably a good idea to take this over to hyper's issue tracker.

**Comment by s-panferov** [comment]
@andor44 yes, could you please make an issue there?

I also would be glad if you give me some common feedback about Rustless and maybe some thoughts about additional features you want.

**Comment by andor44** [comment]
Opened hyperium/hyper#368.

@s-panferov I'll try to collect my thoughts and probably open a separate issue with them in the not too distant future, if that's ok :smiley:
