### ISSUE TITLE
Postgres example in feature/bodyparser, not merged to master

### ISSUE THREAD

**Issue by bguiz** [rustless/rustless#39]
- The readme in master does link to the file, as though it has been merged
- https://github.com/rustless/rustless/blob/feature/bodyparser/examples/postgres/src/main.rs

**Comment by s-panferov** [comment]
Hello @bguiz 	! It's is separate [crate](https://github.com/rustless/rustless-example) now. I'll fix the link, thanks for your report.

**Comment by bguiz** [comment]
Thanks!
