### ISSUE TITLE
Followup: Does not compile with beta

### ISSUE THREAD

**Issue by LukasKalbertodt** [rustless/rustless#40]
From this issue: #38 

This should work before the 1.0 release to ensure it will work with 1.0 as well.

**Comment by flaub** [comment]
To this end, I've updated `queryst` to build with beta with this PR: rustless/queryst#5.

I have begun work on `rustless/valico` but I have one issue remaining, dealing with `mopa`.

**Comment by flaub** [comment]
I've updated `rustless/valico` with PR rustless/valico#10 to work with beta

**Comment by flaub** [comment]
I've updated `mopa` with PR chris-morgan/mopa#2 so it works with beta. Depending on how well this PR is received, I might update the `valico` PR to use `mopa` once again.

**Comment by allan-simon** [comment]
@flaub  thanks, I can't wait for rustless to compile with rustc beta =)

**Comment by s-panferov** [comment]
@flaub thanks again for the great work! I've removed mopa from the rustless.

v0.7.0 works on beta now!

**Comment by allan-simon** [comment]
awesome \o/

**Comment by allan-simon** [comment]
it may be good to precise it in the readme as it an important proof of stability.

**Comment by flaub** [comment]
Great news! It would be good to remove references to the `dsl!` in the README also.
