### ISSUE TITLE
how do i set header for response encoding and set content type as 'application/json'

### ISSUE THREAD

**Issue by allan-simon** [rustless/rustless#47]
if the readme could explain that, it would be great

**Comment by s-panferov** [comment]
You don't need to set content-type by hand, just use https://github.com/rustless/rustless-example/blob/master/src/api/tweets.rs#L20.

To set custom headers please use `.set_header()`, e.g. https://github.com/rustless/rustless/blob/44c0687276861d59f07ab6f60e4a57ef330869b9/src/batteries/swagger.rs#L410

**Comment by allan-simon** [comment]
ok thanks I ended using  the set_header() because I'm doing this 

```
let relevant_words : HashMap<&String, &u8> = word_count.iter().filter(|&(&_, &count)| count > 1).collect();
client.set_header(header::ContentType::json())
client.text(json::encode(&relevant_words).unwrap())
```
and using  client.json() would have required to have a Json object, and i could not have used directly the .to_json() provided by rust_serialize , and I would still have needed to set the encoding to utf-8
