### ISSUE TITLE
Not compiled...

### ISSUE THREAD

**Issue by egorovd** [rustless/rustless#48]
Hello,

In last version iron in Cargo.toml in section dep. set:
https://github.com/iron/iron/commit/26cd9eeedc246d94aee78497f2387f41983c7511

hyper = "0.5"

but in rustless

[dependencies.iron]
version = "*"

And because of this error is obtained:

/home/denis/.cargo/git/checkouts/rustless-7db87dce98c9dc38/master/src/backend/iron.rs:46:45: 46:58 error: mismatched types:
 expected `&hyper::header::Headers`,
    found `&hyper::header::Headers`
(expected struct `hyper::header::Headers`,
    found a different struct `hyper::header::Headers`) [E0308]
/home/denis/.cargo/git/checkouts/rustless-7db87dce98c9dc38/master/src/backend/iron.rs:46     fn headers(&self) -> &header::Headers { &self.headers }
                                                                                                                                     ^~~~~~~~~~~~~
/home/denis/.cargo/git/checkouts/rustless-7db87dce98c9dc38/master/src/backend/iron.rs:47:43: 47:55 error: mismatched types:
 expected `&hyper::method::Method`,
    found `&hyper::method::Method`
(expected enum `hyper::method::Method`,
    found a different enum `hyper::method::Method`) [E0308]
/home/denis/.cargo/git/checkouts/rustless-7db87dce98c9dc38/master/src/backend/iron.rs:47     fn method(&self) -> &method::Method { &self.method }
                                                                                                                                   ^~~~~~~~~~~~
/home/denis/.cargo/git/checkouts/rustless-7db87dce98c9dc38/master/src/backend/iron.rs:66:34: 66:45 error: mismatched types:
 expected `hyper::status::StatusCode`,
    found `hyper::status::StatusCode`
(expected enum `hyper::status::StatusCode`,
    found a different enum `hyper::status::StatusCode`) [E0308]
/home/denis/.cargo/git/checkouts/rustless-7db87dce98c9dc38/master/src/backend/iron.rs:66                     status: Some(resp.status),
                                                                                                                          ^~~~~~~~~~~
/home/denis/.cargo/git/checkouts/rustless-7db87dce98c9dc38/master/src/backend/iron.rs:67:30: 67:42 error: mismatched types:
 expected `hyper::header::Headers`,
    found `hyper::header::Headers`
(expected struct `hyper::header::Headers`,
    found a different struct `hyper::header::Headers`) [E0308]
/home/denis/.cargo/git/checkouts/rustless-7db87dce98c9dc38/master/src/backend/iron.rs:67                     headers: resp.headers,
                                                                                                                      ^~~~~~~~~~~~
/home/denis/.cargo/git/checkouts/rustless-7db87dce98c9dc38/master/src/backend/iron.rs:77:38: 77:53 error: mismatched types:
 expected `hyper::status::StatusCode`,
    found `hyper::status::StatusCode`
(expected enum `hyper::status::StatusCode`,
    found a different enum `hyper::status::StatusCode`) [E0308]
/home/denis/.cargo/git/checkouts/rustless-7db87dce98c9dc38/master/src/backend/iron.rs:77                         status: Some(response.status),
                                                                                                                              ^~~~~~~~~~~~~~~
/home/denis/.cargo/git/checkouts/rustless-7db87dce98c9dc38/master/src/backend/iron.rs:78:34: 78:50 error: mismatched types:
 expected `hyper::header::Headers`,
    found `hyper::header::Headers`
(expected struct `hyper::header::Headers`,
    found a different struct `hyper::header::Headers`) [E0308]
/home/denis/.cargo/git/checkouts/rustless-7db87dce98c9dc38/master/src/backend/iron.rs:78                         headers: response.headers,
                                                                                                                          ^~~~~~~~~~~~~~~~
/home/denis/.cargo/git/checkouts/rustless-7db87dce98c9dc38/master/src/batteries/cookie.rs:56:29: 56:73 error: the trait `hyper::header::Header` is not implemented for the type `
hyper::header::common::set_cookie::SetCookie` [E0277]
/home/denis/.cargo/git/checkouts/rustless-7db87dce98c9dc38/master/src/batteries/cookie.rs:56                 res.headers.set(header::SetCookie::from_cookie_jar(jar));
                                                                                                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/denis/.cargo/git/checkouts/rustless-7db87dce98c9dc38/master/src/batteries/cookie.rs:56:29: 56:73 error: the trait `hyper::header::HeaderFormat` is not implemented for the 
type `hyper::header::common::set_cookie::SetCookie` [E0277]
/home/denis/.cargo/git/checkouts/rustless-7db87dce98c9dc38/master/src/batteries/cookie.rs:56                 res.headers.set(header::SetCookie::from_cookie_jar(jar));
                                                                                                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
error: aborting due to 8 previous errors
Could not compile `rustless`.

Thank you.

**Comment by s-panferov** [comment]
Hi all, sorry for the loooong delay. I've changed my context to another projects, but now I have plans to return to Rustless, because I see real improvements in Rust ecosystem.

Version `v0.8.0` works on latest Rust v1.4 (Stable). Please try it and say what you think!
