### ISSUE TITLE
No longer compiles with nightly

### ISSUE THREAD

**Issue by MarkSwanson** [rustless/rustless#49]
I see this project hasn't had any updates in 4 months; is it still active?
Any interest in patches to get things working with nightly?

src/backend/iron.rs:68:27: 68:36 error: mismatched types:
 expected `core::option::Option<Box<iron::response::WriteBody + Send + 'static>>`,
    found `core::option::Option<Box<std::io::Read + Send + 'static>>`

src/batteries/cookie.rs:41:32: 41:61 error: mismatched types:
 expected `cookie::jar::CookieJar<'_>`,
    found `cookie::jar::CookieJar<'static>`

src/batteries/cookie.rs:56:68: 56:71 error: mismatched types:
 expected `&cookie::jar::CookieJar<'_>`,
    found `&mut cookie::jar::CookieJar<'_>`

**Comment by Byron** [comment]
I am seeing the same issue with Rust 1.2 stable.
Starting at the cookie-jar issue, unfortunately I didn't manage to make any progress towards making it compile. Not writing Rust for a while made me forget how complex things could get ... .

**Comment by s-panferov** [comment]
@MarkSwanson right now I'm not supporting the project, because I don't see any interested users. If you're interested, I can update the project to the latest Rust.

**Comment by Byron** [comment]
The project makes an excellent first impression, and 152 stars mean something too :) ! Now I am using Iron directly, but would have loved to use rustless instead. I even attempted to submit a PR to help making it compile, but couldn't figure out how to handle the `CookieJar`.

**Comment by s-panferov** [comment]
@Byron ok, I'll try to update the project today or tomorrow.

**Comment by MarkSwanson** [comment]
Rustless seems like the best way to get it done atm. I especially like/appreciate the direction to support Swagger 2.0.

**Comment by Byron** [comment]
@s-panferov thanks a bunch !
It seems ticket #48 is related to this one as well.

**Comment by mtorromeo** [comment]
I was also looking forward to start my first serious project in rust with rustless. It's too bad that this is not supported and I would gladly contribute if I was not still a total noob in rust :)

**Comment by NickeZ** [comment]
+1 was going to try this out for my project, also got the same issues with iron.rs and cookie.rs. Are there any workarounds?

**Comment by s-panferov** [comment]
Hi all, sorry for the loooong delay. I've changed my context to another projects, but now I have plans to return to Rustless, because I see real improvements in Rust ecosystem.

Version `v0.8.0` works on latest Rust v1.4 (Stable). Please try it and say what you think!

**Comment by Dashed** [comment]
@s-panferov That's awesome to hear!  Unfortunately, I went with barebones iron when I saw that rustless was *supposedly* abandoned. I definitely might migrate to rustless.
