### ISSUE TITLE
Please use explicit version requirements for dependencies

### ISSUE THREAD

**Issue by badboy** [rustless/rustless#52]
Currently it uses [star versions](https://github.com/rustless/rustless/blob/master/Cargo.toml#L24-L37), which **will** break.

**Comment by zengsai** [comment]
Thanks, I fight for this error today for a long time.

**Comment by s-panferov** [comment]
@badboy I'll try to fix this asap

**Comment by badboy** [comment]
Cool! Thanks for the effort!

**Comment by s-panferov** [comment]
@badboy version v0.7.1 compiles now on the latest Rust stable release.
