### ISSUE TITLE
Move to Serde

### ISSUE THREAD

**Issue by s-panferov** [rustless/rustless#59]
It seems like [`serde`](https://crates.io/crates/serde) (and likewise [`serde_json`](https://crates.io/crates/serde_json)) is becoming the canonical way to serialize/deserialize JSON in rust. Even the `rustc-serialize` docs [say](https://doc.rust-lang.org/rustc-serialize/rustc_serialize/json/index.html#the-status-of-this-library):

> While this library is the standard way of working with JSON in Rust, there is a next-generation library called Serde that's in the works (it's faster, overcomes some design limitations of rustc-serialize and has more features). You might consider using it when starting a new project or evaluating Rust JSON performance.

So I think that rustless must move to Serde too.

**Comment by chpio** [comment]
any progress here, besides that commit in #60?
