### ISSUE TITLE
before/after handler

### ISSUE THREAD

**Issue by chpio** [rustless/rustless#70]
hi,

what is the best way to respond with an error in the before handler? the `error_response!` macro seems to be not exported, so there is no comfortable way to do that?!

**Comment by chpio** [comment]
im doing 
```rust
return Err(ErrorResponse {
	error: Box::new(errors::Body::new("no auth cookie".to_string())),
	response: Some(Response::new(StatusCode::Unauthorized)),
})
```
right now, but i can't get the purpose of the *error* field. is this only for internal use (logging)?

**Comment by s-panferov** [comment]
Rustless don't include any body text to errors by default. You can change this by adding an `error_formatter`.
