### ISSUE TITLE
Owner here: Does community need this crate?

### ISSUE THREAD

**Issue by s-panferov** [rustless/rustless#90]
Please write your opinion: should I continue to develop this crate? Do you want to use this in your application?

**Comment by frol** [comment]
I think, nobody can force you to develop your project. I haven't used this project, but I see a great value in such a framework. The sad point I should bring here is that Iron has also been "abandoned":

> NOTE: Iron is not actively maintained at the moment, please consider using a different framework

Thus, if you choose to continue the development, you will need to consider switching the base framework, which might be painful.

Thanks for the great project! Good luck!
